variant = "strict"

[[entries."source.php".issues]]
code = "function-name"
start_line = 36
end_line = 36

[[entries."source.php".issues]]
code = "function-name"
start_line = 41
end_line = 41

[[entries."source.php".issues]]
code = "function-name"
start_line = 46
end_line = 46

[[entries."source.php".issues]]
code = "function-name"
start_line = 53
end_line = 53

[[entries."source.php".issues]]
code = "function-name"
start_line = 62
end_line = 62

[[entries."source.php".issues]]
code = "no-insecure-comparison"
start_line = 29
end_line = 29

[[entries."source.php".issues]]
code = "no-isset"
start_line = 72
end_line = 72

[[entries."source.php".issues]]
code = "sensitive-parameter"
start_line = 27
end_line = 27

[[entries."source.php".issues]]
code = "sensitive-parameter"
start_line = 36
end_line = 36

[[entries."source.php".issues]]
code = "sensitive-parameter"
start_line = 46
end_line = 46

[[entries."source.php".issues]]
code = "sensitive-parameter"
start_line = 53
end_line = 53

[[entries."source.php".issues]]
code = "single-class-per-file"
start_line = 22
end_line = 22

[[entries."source.php".issues]]
code = "strict-types"
start_line = 0
end_line = 0
