variant = "strict"

[[entries."source.php".issues]]
code = "class-name"
start_line = 4
end_line = 4

[[entries."source.php".issues]]
code = "file-name"
start_line = 4
end_line = 4

[[entries."source.php".issues]]
code = "function-name"
start_line = 9
end_line = 9

[[entries."source.php".issues]]
code = "strict-types"
start_line = 0
end_line = 0
