variant = "strict"

[[entries."source.php".issues]]
code = "no-empty-comment"
start_line = 29
end_line = 30

[[entries."source.php".issues]]
code = "single-class-per-file"
start_line = 17
end_line = 17

[[entries."source.php".issues]]
code = "single-class-per-file"
start_line = 27
end_line = 27

[[entries."source.php".issues]]
code = "strict-types"
start_line = 0
end_line = 0
