variant = "strict"

[[entries."source.php".issues]]
code = "literal-named-argument"
start_line = 7
end_line = 7

[[entries."source.php".issues]]
code = "literal-named-argument"
start_line = 13
end_line = 13

[[entries."source.php".issues]]
code = "literal-named-argument"
start_line = 19
end_line = 19

[[entries."source.php".issues]]
code = "literal-named-argument"
start_line = 25
end_line = 25

[[entries."source.php".issues]]
code = "literal-named-argument"
start_line = 37
end_line = 37

[[entries."source.php".issues]]
code = "literal-named-argument"
start_line = 43
end_line = 43

[[entries."source.php".issues]]
code = "literal-named-argument"
start_line = 49
end_line = 49

[[entries."source.php".issues]]
code = "literal-named-argument"
start_line = 55
end_line = 55

[[entries."source.php".issues]]
code = "literal-named-argument"
start_line = 61
end_line = 61

[[entries."source.php".issues]]
code = "literal-named-argument"
start_line = 67
end_line = 67

[[entries."source.php".issues]]
code = "literal-named-argument"
start_line = 73
end_line = 73

[[entries."source.php".issues]]
code = "literal-named-argument"
start_line = 79
end_line = 79
