extends = "../defaults.toml"

php-version = "8.4"

[source]
paths = ["src"]
includes = ["vendor"]
excludes = []

[linter.rules]
single-class-per-file = { enabled = false }
file-name = { enabled = false }
