variant = "strict"

[[entries."source.php".issues]]
code = "single-class-per-file"
start_line = 9
end_line = 9

[[entries."source.php".issues]]
code = "single-class-per-file"
start_line = 14
end_line = 14

[[entries."source.php".issues]]
code = "single-class-per-file"
start_line = 22
end_line = 22

[[entries."source.php".issues]]
code = "single-class-per-file"
start_line = 24
end_line = 24

[[entries."source.php".issues]]
code = "single-class-per-file"
start_line = 30
end_line = 30

[[entries."source.php".issues]]
code = "single-class-per-file"
start_line = 35
end_line = 35

[[entries."source.php".issues]]
code = "single-class-per-file"
start_line = 44
end_line = 44

[[entries."source.php".issues]]
code = "single-class-per-file"
start_line = 46
end_line = 46
