variant = "strict"

[[entries."source.php".issues]]
code = "single-class-per-file"
start_line = 18
end_line = 18

[[entries."source.php".issues]]
code = "single-class-per-file"
start_line = 29
end_line = 29

[[entries."source.php".issues]]
code = "single-class-per-file"
start_line = 36
end_line = 36

[[entries."source.php".issues]]
code = "single-class-per-file"
start_line = 45
end_line = 45

[[entries."source.php".issues]]
code = "single-class-per-file"
start_line = 53
end_line = 53

[[entries."source.php".issues]]
code = "single-class-per-file"
start_line = 59
end_line = 59

[[entries."source.php".issues]]
code = "single-class-per-file"
start_line = 61
end_line = 61
