variant = "strict"

[[entries."source.php".issues]]
code = "invalid-return-statement"
start_line = 12
end_line = 12

[[entries."source.php".issues]]
code = "null-property-access"
start_line = 12
end_line = 12
