variant = "strict"

[[entries."source.php".issues]]
code = "undefined-string-array-index"
start_line = 8
end_line = 8

[[entries."source.php".issues]]
code = "undefined-string-array-index"
start_line = 15
end_line = 15
