variant = "strict"

[[entries."source.php".issues]]
code = "single-class-per-file"
start_line = 10
end_line = 10

[[entries."source.php".issues]]
code = "single-class-per-file"
start_line = 18
end_line = 18

[[entries."source.php".issues]]
code = "single-class-per-file"
start_line = 24
end_line = 24

[[entries."source.php".issues]]
code = "strict-types"
start_line = 0
end_line = 0
