variant = "strict"

[[entries."source.php".issues]]
code = "possibly-undefined-int-array-index"
start_line = 30
end_line = 30

[[entries."source.php".issues]]
code = "possibly-undefined-int-array-index"
start_line = 31
end_line = 31

[[entries."source.php".issues]]
code = "possibly-undefined-int-array-index"
start_line = 33
end_line = 33

[[entries."source.php".issues]]
code = "possibly-undefined-int-array-index"
start_line = 34
end_line = 34
