variant = "strict"

[[entries."source.php".issues]]
code = "function-name"
start_line = 4
end_line = 4

[[entries."source.php".issues]]
code = "function-name"
start_line = 12
end_line = 12

[[entries."source.php".issues]]
code = "function-name"
start_line = 20
end_line = 20

[[entries."source.php".issues]]
code = "function-name"
start_line = 32
end_line = 32

[[entries."source.php".issues]]
code = "no-else-clause"
start_line = 24
end_line = 26
