variant = "strict"

[[entries."source.php".issues]]
code = "match-not-exhaustive"
start_line = 15
end_line = 15

[[entries."source.php".issues]]
code = "unhandled-thrown-type"
start_line = 15
end_line = 18
