variant = "strict"

[[entries."source.php".issues]]
code = "function-name"
start_line = 7
end_line = 7

[[entries."source.php".issues]]
code = "function-name"
start_line = 23
end_line = 23

[[entries."source.php".issues]]
code = "literal-named-argument"
start_line = 43
end_line = 43

[[entries."source.php".issues]]
code = "no-boolean-flag-parameter"
start_line = 23
end_line = 23

[[entries."source.php".issues]]
code = "no-debug-symbols"
start_line = 40
end_line = 40

[[entries."source.php".issues]]
code = "no-debug-symbols"
start_line = 41
end_line = 41

[[entries."source.php".issues]]
code = "no-empty"
start_line = 29
end_line = 29

[[entries."source.php".issues]]
code = "no-isset"
start_line = 9
end_line = 9

[[entries."source.php".issues]]
code = "no-literal-password"
start_line = 40
end_line = 40

[[entries."source.php".issues]]
code = "no-literal-password"
start_line = 41
end_line = 41
