variant = "strict"

[[entries."source.php".issues]]
code = "no-else-clause"
start_line = 26
end_line = 28

[[entries."source.php".issues]]
code = "single-class-per-file"
start_line = 12
end_line = 12

[[entries."source.php".issues]]
code = "single-class-per-file"
start_line = 17
end_line = 17
