variant = "strict"

[[entries."source.php".issues]]
code = "file-name"
start_line = 4
end_line = 4

[[entries."source.php".issues]]
code = "halstead"
start_line = 39
end_line = 65

[[entries."source.php".issues]]
code = "no-else-clause"
start_line = 52
end_line = 54

[[entries."source.php".issues]]
code = "no-else-clause"
start_line = 56
end_line = 59

[[entries."source.php".issues]]
code = "no-else-clause"
start_line = 59
end_line = 61

[[entries."source.php".issues]]
code = "no-isset"
start_line = 25
end_line = 25

[[entries."source.php".issues]]
code = "no-isset"
start_line = 50
end_line = 50
