variant = "strict"

[[entries."source.php".issues]]
code = "no-isset"
start_line = 8
end_line = 8

[[entries."source.php".issues]]
code = "no-isset"
start_line = 18
end_line = 18

[[entries."source.php".issues]]
code = "strict-types"
start_line = 0
end_line = 0
