variant = "strict"

[[entries."source.php".issues]]
code = "semantics"
start_line = 62
end_line = 62

[[entries."source.php".issues]]
code = "semantics"
start_line = 90
end_line = 90

[[entries."source.php".issues]]
code = "unused-method"
start_line = 6
end_line = 6

[[entries."source.php".issues]]
code = "unused-method"
start_line = 26
end_line = 26
