php_version = "8.1"

[source]
paths = ["composer"]
includes = ["vendor"]
excludes = []

[linter]
default_plugins = true
plugins = ["symfony"]

[[linter.rules]]
name = "maintainability/cyclomatic-complexity"
threshold = 20

[[linter.rules]]
name = "maintainability/kan-defect"
threshold = 1.9

[[linter.rules]]
name = "maintainability/halstead"
effort_threshold = 7000

[[linter.rules]]
name = "best-practices/literal-named-argument"
level = "off"
