variant = "strict"

[[entries."source.php".issues]]
code = "single-class-per-file"
start_line = 29
end_line = 29

[[entries."source.php".issues]]
code = "single-class-per-file"
start_line = 42
end_line = 42

[[entries."source.php".issues]]
code = "strict-types"
start_line = 0
end_line = 0
