variant = "strict"

[[entries."source.php".issues]]
code = "no-debug-symbols"
start_line = 34
end_line = 34

[[entries."source.php".issues]]
code = "single-class-per-file"
start_line = 6
end_line = 6

[[entries."source.php".issues]]
code = "single-class-per-file"
start_line = 12
end_line = 12
