variant = "strict"

[[entries."source.php".issues]]
code = "missing-constructor"
start_line = 12
end_line = 12

[[entries."source.php".issues]]
code = "missing-constructor"
start_line = 20
end_line = 20
