variant = "strict"

[[entries."source.php".issues]]
code = "file-name"
start_line = 9
end_line = 9

[[entries."source.php".issues]]
code = "no-boolean-flag-parameter"
start_line = 45
end_line = 45

[[entries."source.php".issues]]
code = "strict-types"
start_line = 0
end_line = 0
