variant = "strict"

[[entries."source.php".issues]]
code = "single-class-per-file"
start_line = 4
end_line = 4

[[entries."source.php".issues]]
code = "single-class-per-file"
start_line = 6
end_line = 6

[[entries."source.php".issues]]
code = "single-class-per-file"
start_line = 11
end_line = 11

[[entries."source.php".issues]]
code = "single-class-per-file"
start_line = 16
end_line = 16

[[entries."source.php".issues]]
code = "single-class-per-file"
start_line = 21
end_line = 21

[[entries."source.php".issues]]
code = "single-class-per-file"
start_line = 26
end_line = 26

[[entries."source.php".issues]]
code = "strict-types"
start_line = 0
end_line = 0
