variant = "strict"

[[entries."source.php".issues]]
code = "braced-string-interpolation"
start_line = 46
end_line = 46

[[entries."source.php".issues]]
code = "braced-string-interpolation"
start_line = 52
end_line = 52

[[entries."source.php".issues]]
code = "no-else-clause"
start_line = 59
end_line = 61

[[entries."source.php".issues]]
code = "single-class-per-file"
start_line = 8
end_line = 8

[[entries."source.php".issues]]
code = "strict-types"
start_line = 0
end_line = 0
