variant = "strict"

[[entries."source.php".issues]]
code = "impossible-assignment"
start_line = 43
end_line = 43

[[entries."source.php".issues]]
code = "invalid-property-read"
start_line = 43
end_line = 43

[[entries."source.php".issues]]
code = "invalid-property-write"
start_line = 30
end_line = 30
