variant = "strict"

[[entries."source.php".issues]]
code = "reference-constraint-violation"
start_line = 6
end_line = 6

[[entries."source.php".issues]]
code = "reference-constraint-violation"
start_line = 15
end_line = 15
