variant = "strict"

[[entries."source.php".issues]]
code = "no-redundant-method-override"
start_line = 9
end_line = 12

[[entries."source.php".issues]]
code = "single-class-per-file"
start_line = 15
end_line = 15

[[entries."source.php".issues]]
code = "single-class-per-file"
start_line = 20
end_line = 20
