variant = "strict"

[[entries."source.php".issues]]
code = "function-name"
start_line = 5
end_line = 5

[[entries."source.php".issues]]
code = "function-name"
start_line = 17
end_line = 17

[[entries."source.php".issues]]
code = "strict-types"
start_line = 0
end_line = 0
