variant = "strict"

[[entries."source.php".issues]]
code = "single-class-per-file"
start_line = 7
end_line = 7

[[entries."source.php".issues]]
code = "single-class-per-file"
start_line = 13
end_line = 13

[[entries."source.php".issues]]
code = "single-class-per-file"
start_line = 20
end_line = 20

[[entries."source.php".issues]]
code = "single-class-per-file"
start_line = 27
end_line = 27

[[entries."source.php".issues]]
code = "single-class-per-file"
start_line = 29
end_line = 29

[[entries."source.php".issues]]
code = "single-class-per-file"
start_line = 36
end_line = 36

[[entries."source.php".issues]]
code = "single-class-per-file"
start_line = 38
end_line = 38

[[entries."source.php".issues]]
code = "single-class-per-file"
start_line = 45
end_line = 45

[[entries."source.php".issues]]
code = "single-class-per-file"
start_line = 50
end_line = 50

[[entries."source.php".issues]]
code = "single-class-per-file"
start_line = 52
end_line = 52
