variant = "strict"

[[entries."source.php".issues]]
code = "impossible-condition"
start_line = 20
end_line = 20

[[entries."source.php".issues]]
code = "redundant-condition"
start_line = 19
end_line = 19
