variant = "strict"

[[entries."source.php".issues]]
code = "braced-string-interpolation"
start_line = 38
end_line = 38

[[entries."source.php".issues]]
code = "file-name"
start_line = 10
end_line = 10

[[entries."source.php".issues]]
code = "strict-types"
start_line = 0
end_line = 0
