variant = "strict"

[[entries."source.php".issues]]
code = "literal-named-argument"
start_line = 9
end_line = 9

[[entries."source.php".issues]]
code = "literal-named-argument"
start_line = 10
end_line = 10

[[entries."source.php".issues]]
code = "literal-named-argument"
start_line = 11
end_line = 11
