[package]
name = "mago-typing"
description = "Provides basic type inference for PHP code, deducing variable and return types to assist in static analysis and automated tooling."
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
mago-syntax = { workspace = true }
mago-reflection = { workspace = true }
mago-source = { workspace = true }
mago-span = { workspace = true }
mago-names = { workspace = true }
mago-interner = { workspace = true }
mago-trinary = { workspace = true }
ahash = { workspace = true }
ordered-float = { workspace = true }
