variant = "strict"

[[entries."source.php".issues]]
code = "mixed-return-statement"
start_line = 16
end_line = 16

[[entries."source.php".issues]]
code = "possible-method-access-on-null"
start_line = 16
end_line = 16
