variant = "strict"

[[entries."source.php".issues]]
code = "mixed-assignment"
start_line = 7
end_line = 7

[[entries."source.php".issues]]
code = "possibly-undefined-string-array-index"
start_line = 7
end_line = 7
