variant = "strict"

[[entries."source.php".issues]]
code = "file-name"
start_line = 45
end_line = 45

[[entries."source.php".issues]]
code = "no-empty-comment"
start_line = 58
end_line = 59

[[entries."source.php".issues]]
code = "no-empty-comment"
start_line = 65
end_line = 66

[[entries."source.php".issues]]
code = "no-empty-comment"
start_line = 72
end_line = 73

[[entries."source.php".issues]]
code = "no-empty-comment"
start_line = 79
end_line = 80

[[entries."source.php".issues]]
code = "no-empty-comment"
start_line = 87
end_line = 88

[[entries."source.php".issues]]
code = "no-empty-comment"
start_line = 94
end_line = 95

[[entries."source.php".issues]]
code = "no-empty-comment"
start_line = 102
end_line = 103

[[entries."source.php".issues]]
code = "no-empty-comment"
start_line = 109
end_line = 110

[[entries."source.php".issues]]
code = "no-empty-comment"
start_line = 116
end_line = 117

[[entries."source.php".issues]]
code = "no-empty-comment"
start_line = 123
end_line = 124

[[entries."source.php".issues]]
code = "no-empty-comment"
start_line = 130
end_line = 131

[[entries."source.php".issues]]
code = "no-empty-comment"
start_line = 137
end_line = 138

[[entries."source.php".issues]]
code = "no-empty-comment"
start_line = 144
end_line = 145

[[entries."source.php".issues]]
code = "strict-types"
start_line = 0
end_line = 0
