variant = "strict"

[[entries."source.php".issues]]
code = "match-not-exhaustive"
start_line = 27
end_line = 27

[[entries."source.php".issues]]
code = "unhandled-thrown-type"
start_line = 27
end_line = 34
