variant = "strict"

[[entries."source.php".issues]]
code = "single-class-per-file"
start_line = 25
end_line = 25

[[entries."source.php".issues]]
code = "single-class-per-file"
start_line = 56
end_line = 56

[[entries."source.php".issues]]
code = "single-class-per-file"
start_line = 81
end_line = 81

[[entries."source.php".issues]]
code = "strict-types"
start_line = 0
end_line = 0
