variant = "strict"

[[entries."source.php".issues]]
code = "function-name"
start_line = 38
end_line = 38

[[entries."source.php".issues]]
code = "no-empty-comment"
start_line = 57
end_line = 57

[[entries."source.php".issues]]
code = "single-class-per-file"
start_line = 9
end_line = 9

[[entries."source.php".issues]]
code = "single-class-per-file"
start_line = 21
end_line = 21
