variant = "strict"

[[entries."source.php".issues]]
code = "invalid-operand"
start_line = 16
end_line = 16

[[entries."source.php".issues]]
code = "mismatched-array-index"
start_line = 16
end_line = 16
