variant = "strict"

[[entries."source.php".issues]]
code = "class-name"
start_line = 29
end_line = 29

[[entries."source.php".issues]]
code = "interface-name"
start_line = 17
end_line = 17

[[entries."source.php".issues]]
code = "single-class-per-file"
start_line = 29
end_line = 29
