variant = "strict"

[[entries."source.php".issues]]
code = "named-argument-overrides-positional"
start_line = 9
end_line = 9

[[entries."source.php".issues]]
code = "too-many-arguments"
start_line = 9
end_line = 9
