//! Runs a compiled pattern against a parsed file and collects matches.

use std::path::Path;

use grit_pattern_matcher::file_owners::FileOwners;
use grit_pattern_matcher::pattern::FileRegistry;
use grit_pattern_matcher::pattern::Matcher;
use grit_pattern_matcher::pattern::ResolvedPattern;
use grit_pattern_matcher::pattern::State;
use grit_util::AnalysisLogs;
use grit_util::AstNode as _;
use grit_util::ByteRange;
use mago_database::file::FileId;
use mago_span::Span;

use crate::compiler::CompiledPattern;
use crate::compiler::build_var_registry;
use crate::context::MagoExecContext;
use crate::language::MagoLanguage;
use crate::node::MagoIndex;
use crate::node::MagoNode;
use crate::query_context::MagoQueryContext;
use crate::resolved_pattern::MagoResolvedPattern;

/// Number of reserved slots grit expects at the front of scope 0.
pub(crate) const RESERVED_SLOT_COUNT: usize = 4;

/// A single match produced by a pattern query.
#[derive(Debug, Clone)]
pub struct Match {
    /// Byte range of the matched node in the target file.
    pub range: ByteRange,
    /// Span of the matched node, convenient for `mago-reporting`.
    pub span: Span,
    /// Captured metavariable values. Each entry is the bound node's source text.
    pub captures: Vec<(String, String)>,
    /// Rewrites generated by `=>` clauses inside the pattern. Each entry is the
    /// `(target range, replacement text)` pair ready to be converted to a `TextEdit`.
    /// Empty when the pattern has no rewrite clauses.
    pub rewrites: Vec<Rewrite>,
}

/// A single text-level rewrite: a byte range to replace and the replacement text.
#[derive(Debug, Clone)]
pub struct Rewrite {
    pub range: ByteRange,
    pub replacement: String,
}

/// Error produced while running a compiled pattern against a target file.
#[derive(Debug, Clone)]
pub struct QueryError {
    /// Human-readable description of what went wrong.
    pub message: String,
}

impl std::fmt::Display for QueryError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(&self.message)
    }
}

impl std::error::Error for QueryError {}

/// Runs the compiled pattern against every descendant of the target program's root.
///
/// # Lifetimes
///
/// `'a` covers the arena the target program was parsed into, the source text, and the
/// index. The `Arc<MagoIndex>` is shared: cloning is cheap and lets the engine's tree own
/// its own handle.
pub fn query<'ctx>(
    compiled: &'ctx CompiledPattern,
    index: &'ctx MagoIndex<'ctx>,
    file_name: &'ctx Path,
) -> Result<Vec<Match>, QueryError> {
    let language = MagoLanguage::new();
    let owners = FileOwners::<crate::tree::MagoTree<'_>>::new();
    let file_registry: FileRegistry<'_, MagoQueryContext> = FileRegistry::new_from_paths(vec![file_name]);
    let context = MagoExecContext::new(&language, &owners);

    let registry = build_var_registry(compiled);
    // `base_state` is a fresh template we clone before each attempt so capture bindings
    // from one node don't leak into the next. The engine's `Variable` matcher enforces
    // equality across repeated captures *within* a single match, which is what we want;
    // it must not enforce them across separate match attempts.
    let base_state = State::<MagoQueryContext>::new(registry, file_registry);

    let mut matches = Vec::new();
    let mut logs = AnalysisLogs::default();

    for id in index.iter_ids() {
        let node = MagoNode::new(index, id);
        let binding = MagoResolvedPattern::from_node_binding(node);

        let mut trial_state = base_state.clone();
        match compiled.pattern.execute(&binding, &mut trial_state, &context, &mut logs) {
            Ok(true) => {
                let range = node.byte_range();
                let start = mago_span::Position::new(range.start as u32);
                let end = mago_span::Position::new(range.end as u32);
                let span = Span::new(FileId::zero(), start, end);
                let captures = extract_captures(compiled, &trial_state, &language);
                let rewrites = extract_rewrites(&trial_state, &language);
                matches.push(Match { range, span, captures, rewrites });
            }
            Ok(false) => {}
            Err(err) => {
                return Err(QueryError { message: format!("pattern execution failed: {err}") });
            }
        }
    }

    Ok(matches)
}

/// Pull the queued rewrite effects out of the state, convert each to a text-level
/// `Rewrite { range, replacement }` ready to be applied via `mago-text-edit`.
fn extract_rewrites<'a>(state: &State<'a, MagoQueryContext>, language: &MagoLanguage) -> Vec<Rewrite> {
    use grit_pattern_matcher::binding::Binding;

    let mut out = Vec::new();
    for effect in &state.effects {
        let Some(range) = effect.binding.range(language) else {
            continue;
        };
        let Ok(text) = effect.pattern.text(&state.files, language) else {
            continue;
        };
        out.push(Rewrite { range, replacement: text.into_owned() });
    }
    out
}

/// Pull captured metavariable values out of the state after a successful match.
fn extract_captures<'a>(
    compiled: &'a CompiledPattern,
    state: &State<'a, MagoQueryContext>,
    language: &MagoLanguage,
) -> Vec<(String, String)> {
    let mut out = Vec::new();
    let Some(scope) = state.bindings.first().and_then(|s| s.last()) else {
        return out;
    };
    for (i, name) in compiled.variables.iter().enumerate() {
        let slot_index = RESERVED_SLOT_COUNT + i;
        let Some(slot) = scope.get(slot_index) else {
            continue;
        };
        let Some(value) = slot.value.as_ref() else {
            continue;
        };
        match value.text(&state.files, language) {
            Ok(text) => out.push((name.clone(), text.into_owned())),
            Err(_) => out.push((name.clone(), String::new())),
        }
    }
    out
}
