name: "Bug Report"
description: "Report a bug or unexpected behavior in Mago."
labels: ["Type: Bug"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Please provide a clear description and reproduction steps. For analyzer or linter issues, use the [Playground](https://mago.carthage.software/playground) to create a shareable reproduction link.

  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: "What happened? What did you expect?"
      placeholder: "Mago reports a false positive for..."
    validations:
      required: true

  - type: input
    id: playground
    attributes:
      label: "Playground Link"
      description: "Share a [Playground](https://mago.carthage.software/playground) link that reproduces the issue (if applicable)."
      placeholder: "https://mago.carthage.software/playground#..."
    validations:
      required: false

  - type: textarea
    id: reproduction
    attributes:
      label: "Reproduction"
      description: "If playground doesn't apply (e.g., formatter, CLI, or config-specific issues), provide steps and code to reproduce."
      placeholder: |
        1. Create a file with...
        2. Run `mago lint`...
    validations:
      required: false

  - type: textarea
    id: environment
    attributes:
      label: "Environment"
      description: "Mago version, OS, and installation method."
      placeholder: |
        - Mago: 1.y.z-rc.2
        - OS: macOS / Linux / Windows
        - Installed via: Homebrew / Cargo / Composer
    validations:
      required: true
