name: "Feature Request"
description: "Suggest a new feature or improvement for Mago."
labels: ["Type: Enhancement"]
assignees: []
body:
  - type: textarea
    id: feature-description
    attributes:
      label: "Feature"
      description: "What feature would you like? What problem does it solve?"
      placeholder: "I'd like Mago to support..."
    validations:
      required: true

  - type: textarea
    id: example
    attributes:
      label: "Example"
      description: "Show an example of how this feature would work (code, config, CLI usage, etc.)."
      render: php
      placeholder: |
        <?php

        // Example code showing the desired behavior
    validations:
      required: false
