variant = "strict"

[[entries."source.php".issues]]
code = "single-class-per-file"
start_line = 44
end_line = 44

[[entries."source.php".issues]]
code = "single-class-per-file"
start_line = 54
end_line = 54
