variant = "strict"

[[entries."source.php".issues]]
code = "list-destructure-string-key"
start_line = 12
end_line = 12

[[entries."source.php".issues]]
code = "mismatched-array-index"
start_line = 12
end_line = 12

[[entries."source.php".issues]]
code = "possibly-undefined-int-array-index"
start_line = 12
end_line = 12
