variant = "strict"

[[entries."source.php".issues]]
code = "file-name"
start_line = 2
end_line = 2

[[entries."source.php".issues]]
code = "no-empty-comment"
start_line = 9
end_line = 10

[[entries."source.php".issues]]
code = "no-empty-comment"
start_line = 21
end_line = 22

[[entries."source.php".issues]]
code = "strict-types"
start_line = 0
end_line = 0
