variant = "strict"

[[entries."source.php".issues]]
code = "single-class-per-file"
start_line = 28
end_line = 28

[[entries."source.php".issues]]
code = "single-class-per-file"
start_line = 53
end_line = 53

[[entries."source.php".issues]]
code = "single-class-per-file"
start_line = 59
end_line = 59
