variant = "strict"

[[entries."source.php".issues]]
code = "impossible-condition"
start_line = 3
end_line = 3

[[entries."source.php".issues]]
code = "redundant-comparison"
start_line = 3
end_line = 3
