variant = "strict"

[[entries."source.php".issues]]
code = "too-few-arguments"
start_line = 28
end_line = 28

[[entries."source.php".issues]]
code = "too-many-arguments"
start_line = 26
end_line = 26
