variant = "strict"

[[entries."source.php".issues]]
code = "literal-named-argument"
start_line = 52
end_line = 52

[[entries."source.php".issues]]
code = "single-class-per-file"
start_line = 13
end_line = 13

[[entries."source.php".issues]]
code = "single-class-per-file"
start_line = 62
end_line = 62

[[entries."source.php".issues]]
code = "single-class-per-file"
start_line = 89
end_line = 89
