variant = "strict"

[[entries."source.php".issues]]
code = "inline-variable-return"
start_line = 28
end_line = 28

[[entries."source.php".issues]]
code = "no-empty-comment"
start_line = 12
end_line = 13

[[entries."source.php".issues]]
code = "single-class-per-file"
start_line = 14
end_line = 14

[[entries."source.php".issues]]
code = "single-class-per-file"
start_line = 34
end_line = 34

[[entries."source.php".issues]]
code = "single-class-per-file"
start_line = 46
end_line = 46

[[entries."source.php".issues]]
code = "single-class-per-file"
start_line = 57
end_line = 57
