variant = "strict"

[[entries."source.php".issues]]
code = "single-class-per-file"
start_line = 8
end_line = 8

[[entries."source.php".issues]]
code = "single-class-per-file"
start_line = 14
end_line = 14

[[entries."source.php".issues]]
code = "single-class-per-file"
start_line = 17
end_line = 17

[[entries."source.php".issues]]
code = "single-class-per-file"
start_line = 21
end_line = 21

[[entries."source.php".issues]]
code = "single-class-per-file"
start_line = 25
end_line = 25

[[entries."source.php".issues]]
code = "single-class-per-file"
start_line = 28
end_line = 28

[[entries."source.php".issues]]
code = "single-class-per-file"
start_line = 30
end_line = 30

[[entries."source.php".issues]]
code = "single-class-per-file"
start_line = 33
end_line = 33

[[entries."source.php".issues]]
code = "single-class-per-file"
start_line = 36
end_line = 36

[[entries."source.php".issues]]
code = "single-class-per-file"
start_line = 39
end_line = 39

[[entries."source.php".issues]]
code = "single-class-per-file"
start_line = 42
end_line = 42

[[entries."source.php".issues]]
code = "single-class-per-file"
start_line = 45
end_line = 45

[[entries."source.php".issues]]
code = "single-class-per-file"
start_line = 51
end_line = 51

[[entries."source.php".issues]]
code = "strict-types"
start_line = 0
end_line = 0
