variant = "strict"

[[entries."source.php".issues]]
code = "function-name"
start_line = 8
end_line = 8

[[entries."source.php".issues]]
code = "function-name"
start_line = 20
end_line = 20

[[entries."source.php".issues]]
code = "function-name"
start_line = 37
end_line = 37

[[entries."source.php".issues]]
code = "function-name"
start_line = 46
end_line = 46
