variant = "strict"

[[entries."source.php".issues]]
code = "single-class-per-file"
start_line = 24
end_line = 24

[[entries."source.php".issues]]
code = "single-class-per-file"
start_line = 32
end_line = 32

[[entries."source.php".issues]]
code = "single-class-per-file"
start_line = 56
end_line = 56
