variant = "strict"

[[entries."source.php".issues]]
code = "abstract-instantiation"
start_line = 8
end_line = 8

[[entries."source.php".issues]]
code = "impossible-assignment"
start_line = 8
end_line = 8
