variant = "strict"

[[entries."source.php".issues]]
code = "function-name"
start_line = 36
end_line = 36

[[entries."source.php".issues]]
code = "single-class-per-file"
start_line = 14
end_line = 14

[[entries."source.php".issues]]
code = "single-class-per-file"
start_line = 22
end_line = 22
