variant = "strict"

[[entries."source.php".issues]]
code = "no-empty-comment"
start_line = 19
end_line = 20

[[entries."source.php".issues]]
code = "no-empty-comment"
start_line = 28
end_line = 29

[[entries."source.php".issues]]
code = "no-empty-comment"
start_line = 37
end_line = 38

[[entries."source.php".issues]]
code = "single-class-per-file"
start_line = 9
end_line = 9

[[entries."source.php".issues]]
code = "strict-types"
start_line = 0
end_line = 0
