variant = "strict"

[[entries."source.php".issues]]
code = "invalid-return-statement"
start_line = 8
end_line = 8

[[entries."source.php".issues]]
code = "nullable-return-statement"
start_line = 8
end_line = 8
