variant = "strict"

[[entries."source.php".issues]]
code = "missing-return-statement"
start_line = 6
end_line = 6

[[entries."source.php".issues]]
code = "missing-return-statement"
start_line = 15
end_line = 15

[[entries."source.php".issues]]
code = "missing-return-statement"
start_line = 95
end_line = 95

[[entries."source.php".issues]]
code = "missing-return-statement"
start_line = 108
end_line = 108
