variant = "strict"

[[entries."source.php".issues]]
code = "function-name"
start_line = 24
end_line = 24

[[entries."source.php".issues]]
code = "function-name"
start_line = 29
end_line = 29

[[entries."source.php".issues]]
code = "single-class-per-file"
start_line = 4
end_line = 4

[[entries."source.php".issues]]
code = "single-class-per-file"
start_line = 6
end_line = 6

[[entries."source.php".issues]]
code = "strict-types"
start_line = 0
end_line = 0
