//! Minimal reader for the compiled Symfony container XML dump.
//!
//! The dump (`var/cache/<env>/App_Kernel*Container.xml`, written by
//! Symfony's `XmlDumper`) lists every service definition and alias of the
//! compiled container. This module extracts the only facts the analyzer
//! needs — service id, class, and alias target — into a flat id → class map.
//!
//! This is deliberately not a general-purpose XML parser: the input is
//! machine-generated by a single writer, and every failure mode is
//! fail-open — an entry that cannot be understood is skipped, and a file
//! that cannot be read produces no map — so the provider built on top of
//! this map can never emit a false positive because of a parsing gap.

use std::borrow::Cow;
use std::path::Path;

use foldhash::HashMap;

use mago_word::Word;
use mago_word::word;

/// Maximum number of alias hops followed when flattening alias chains.
const MAX_ALIAS_HOPS: usize = 16;

/// Map from service id to the fully-qualified class name of the service.
///
/// Aliases are flattened at construction time, so lookups are a single
/// hash-map access.
#[derive(Debug, Default)]
pub struct ServiceMap {
    classes: HashMap<Vec<u8>, Word>,
}

impl ServiceMap {
    /// Loads the map from a compiled container XML dump on disk.
    ///
    /// Returns `None` — after logging a warning — when the file cannot be
    /// read; the caller is expected to skip registration in that case.
    #[must_use]
    pub fn load(path: &Path) -> Option<Self> {
        match std::fs::read_to_string(path) {
            Ok(xml) => Some(Self::from_xml(&xml)),
            Err(error) => {
                tracing::warn!("Failed to read the Symfony container XML dump at `{}`: {error}", path.display());

                None
            }
        }
    }

    /// Parses the map out of the container XML text.
    #[must_use]
    pub fn from_xml(xml: &str) -> Self {
        let mut classes: HashMap<Vec<u8>, Word> = HashMap::default();
        let mut aliases: HashMap<Vec<u8>, Vec<u8>> = HashMap::default();

        for tag in ServiceTags::new(xml.as_bytes()) {
            let Some(id) = tag.id else {
                continue;
            };

            if let Some(alias) = tag.alias {
                aliases.insert(id.into_owned(), alias.into_owned());
            } else if let Some(class) = tag.class {
                let class = class.as_ref().strip_prefix(b"\\").unwrap_or(class.as_ref());
                if !class.is_empty() {
                    classes.insert(id.into_owned(), word(class));
                }
            }
        }

        // Flatten alias chains (alias → … → service) into direct entries.
        for (id, target) in &aliases {
            let mut target = target;

            for _ in 0..MAX_ALIAS_HOPS {
                if let Some(class) = classes.get(target) {
                    classes.insert(id.clone(), *class);
                    break;
                }

                match aliases.get(target) {
                    Some(next) => target = next,
                    None => break,
                }
            }
        }

        Self { classes }
    }

    /// Resolves a service id to the fully-qualified class name of the
    /// service, following aliases.
    ///
    /// Returns `None` for ids the container does not know about.
    #[must_use]
    pub fn class_of(&self, id: &[u8]) -> Option<Word> {
        self.classes.get(id).copied()
    }

    /// Returns the number of resolvable service ids.
    #[must_use]
    pub fn len(&self) -> usize {
        self.classes.len()
    }

    /// Returns `true` when the map contains no resolvable service id.
    #[must_use]
    pub fn is_empty(&self) -> bool {
        self.classes.is_empty()
    }
}

/// The attributes of one `<service …>` tag that the analyzer cares about.
#[derive(Debug, Default)]
struct ServiceTag<'xml> {
    id: Option<Cow<'xml, [u8]>>,
    class: Option<Cow<'xml, [u8]>>,
    alias: Option<Cow<'xml, [u8]>>,
}

/// Iterator over every `<service …>` tag of the dump.
struct ServiceTags<'xml> {
    bytes: &'xml [u8],
    position: usize,
}

impl<'xml> ServiceTags<'xml> {
    const fn new(bytes: &'xml [u8]) -> Self {
        Self { bytes, position: 0 }
    }
}

impl<'xml> Iterator for ServiceTags<'xml> {
    type Item = ServiceTag<'xml>;

    fn next(&mut self) -> Option<Self::Item> {
        const OPENING: &[u8] = b"<service";

        while self.position < self.bytes.len() {
            let offset = memchr::memmem::find(self.bytes.get(self.position..)?, OPENING)?;
            let name_end = self.position + offset + OPENING.len();

            // `<service` must be followed by whitespace or the tag end,
            // otherwise this is another element (e.g. `<services>`).
            match self.bytes.get(name_end) {
                Some(b' ' | b'\t' | b'\r' | b'\n' | b'/' | b'>') => {}
                _ => {
                    self.position = name_end;
                    continue;
                }
            }

            let Some(tag_end) = tag_end(self.bytes, name_end) else {
                // Unterminated tag: nothing more to read.
                self.position = self.bytes.len();
                return None;
            };

            self.position = tag_end + 1;

            let region = self.bytes.get(name_end..tag_end)?;

            return Some(parse_service_tag(region));
        }

        None
    }
}

/// Finds the position of the `>` closing the tag, honoring quoted
/// attribute values.
fn tag_end(bytes: &[u8], from: usize) -> Option<usize> {
    let mut quote: Option<u8> = None;

    for (position, &byte) in bytes.iter().enumerate().skip(from) {
        match quote {
            Some(q) => {
                if byte == q {
                    quote = None;
                }
            }
            None => match byte {
                b'"' | b'\'' => quote = Some(byte),
                b'>' => return Some(position),
                _ => {}
            },
        }
    }

    None
}

/// Parses the attribute region of a `<service …>` tag, keeping only the
/// `id`, `class`, and `alias` attributes. Anything malformed ends the scan:
/// fail-open, never a guess.
fn parse_service_tag(region: &[u8]) -> ServiceTag<'_> {
    let mut tag = ServiceTag::default();
    let mut position = 0;

    loop {
        position = skip_whitespace(region, position);

        let name_start = position;
        while region.get(position).is_some_and(|byte| !byte.is_ascii_whitespace() && *byte != b'=') {
            position += 1;
        }

        let name = region.get(name_start..position).unwrap_or_default();
        if name.is_empty() || name == b"/" {
            break;
        }

        position = skip_whitespace(region, position);
        if region.get(position) != Some(&b'=') {
            break;
        }

        position = skip_whitespace(region, position + 1);
        let Some(&quote @ (b'"' | b'\'')) = region.get(position) else {
            break;
        };

        position += 1;
        let value_start = position;
        let Some(length) = memchr::memchr(quote, region.get(value_start..).unwrap_or_default()) else {
            break;
        };

        position = value_start + length + 1;

        let value = region.get(value_start..value_start + length).unwrap_or_default();
        match name {
            b"id" => tag.id = Some(unescape(value)),
            b"class" => tag.class = Some(unescape(value)),
            b"alias" => tag.alias = Some(unescape(value)),
            _ => {}
        }
    }

    tag
}

fn skip_whitespace(bytes: &[u8], mut position: usize) -> usize {
    while bytes.get(position).is_some_and(u8::is_ascii_whitespace) {
        position += 1;
    }

    position
}

/// Replaces the five predefined XML entities. Unknown entities are kept
/// as-is: service ids and class names never contain them in practice.
fn unescape(value: &[u8]) -> Cow<'_, [u8]> {
    const ENTITIES: [(&[u8], u8); 5] =
        [(b"&amp;", b'&'), (b"&lt;", b'<'), (b"&gt;", b'>'), (b"&quot;", b'"'), (b"&apos;", b'\'')];

    if !value.contains(&b'&') {
        return Cow::Borrowed(value);
    }

    let mut unescaped = Vec::with_capacity(value.len());
    let mut position = 0;

    while let Some(&byte) = value.get(position) {
        if byte == b'&'
            && let Some((entity, replacement)) =
                ENTITIES.iter().find(|(entity, _)| value.get(position..).is_some_and(|rest| rest.starts_with(entity)))
        {
            unescaped.push(*replacement);
            position += entity.len();
            continue;
        }

        unescaped.push(byte);
        position += 1;
    }

    Cow::Owned(unescaped)
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The minimal shape of a compiled dump: two services and one alias.
    const FIXTURE: &str = r#"<?xml version="1.0" encoding="utf-8"?>
<container xmlns="http://symfony.com/schema/dic/services">
  <parameters>
    <parameter key="kernel.debug" type="binary">MQ==</parameter>
  </parameters>
  <services>
    <service id="service_container" class="Symfony\Component\DependencyInjection\ContainerInterface" public="true" synthetic="true"/>
    <service id="app.mailer" class="App\Service\Mailer" public="true">
      <argument type="service" id="app.transport"/>
    </service>
    <service id="app.transport" class="App\Service\SmtpTransport"/>
    <service id="App\Service\MailerInterface" alias="app.mailer" public="true"/>
  </services>
</container>
"#;

    #[test]
    fn resolves_a_service_id_to_its_class() {
        let map = ServiceMap::from_xml(FIXTURE);

        assert_eq!(map.class_of(b"app.mailer"), Some(word("App\\Service\\Mailer")));
        assert_eq!(map.class_of(b"app.transport"), Some(word("App\\Service\\SmtpTransport")));
    }

    #[test]
    fn resolves_an_alias_to_the_aliased_service_class() {
        let map = ServiceMap::from_xml(FIXTURE);

        assert_eq!(map.class_of(b"App\\Service\\MailerInterface"), Some(word("App\\Service\\Mailer")));
    }

    #[test]
    fn unknown_ids_have_no_class() {
        let map = ServiceMap::from_xml(FIXTURE);

        assert_eq!(map.class_of(b"app.unknown"), None);
        assert_eq!(map.len(), 4);
    }

    #[test]
    fn argument_service_references_are_not_services() {
        // `<argument type="service" id="app.transport"/>` must not shadow
        // or duplicate the real definition.
        let map = ServiceMap::from_xml(FIXTURE);

        assert!(!map.is_empty());
        assert_eq!(map.class_of(b"service"), None);
    }

    #[test]
    fn alias_chains_are_flattened() {
        let map = ServiceMap::from_xml(
            r#"<services>
                 <service id="a" alias="b"/>
                 <service id="b" alias="c"/>
                 <service id="c" class="App\Leaf"/>
               </services>"#,
        );

        assert_eq!(map.class_of(b"a"), Some(word("App\\Leaf")));
        assert_eq!(map.class_of(b"b"), Some(word("App\\Leaf")));
    }

    #[test]
    fn alias_cycles_do_not_hang_or_resolve() {
        let map = ServiceMap::from_xml(
            r#"<services>
                 <service id="a" alias="b"/>
                 <service id="b" alias="a"/>
               </services>"#,
        );

        assert_eq!(map.class_of(b"a"), None);
        assert_eq!(map.class_of(b"b"), None);
    }

    #[test]
    fn leading_backslash_is_stripped_from_class_names() {
        let map = ServiceMap::from_xml(r#"<services><service id="x" class="\App\Thing"/></services>"#);

        assert_eq!(map.class_of(b"x"), Some(word("App\\Thing")));
    }

    #[test]
    fn quoted_entities_are_unescaped() {
        let map = ServiceMap::from_xml(r#"<services><service id="a&amp;b" class="App\A"/></services>"#);

        assert_eq!(map.class_of(b"a&b"), Some(word("App\\A")));
    }

    #[test]
    fn tags_without_id_or_class_are_skipped() {
        let map = ServiceMap::from_xml(
            r#"<services>
                 <service class="App\NoId"/>
                 <service id="no.class"/>
                 <service id="broken class="App\Broken"/>
               </services>"#,
        );

        assert_eq!(map.class_of(b"no.class"), None);
        assert!(map.is_empty());
    }

    #[test]
    fn angle_bracket_inside_attribute_value_does_not_end_the_tag() {
        let map = ServiceMap::from_xml(r#"<services><service id="odd>id" class="App\Odd"/></services>"#);

        assert_eq!(map.class_of(b"odd>id"), Some(word("App\\Odd")));
    }

    #[test]
    fn empty_input_yields_an_empty_map() {
        assert!(ServiceMap::from_xml("").is_empty());
        assert!(ServiceMap::from_xml("<container/>").is_empty());
    }
}
