variant = "strict"

[[entries."source.php".issues]]
code = "write-only-property"
start_line = 6
end_line = 6

[[entries."source.php".issues]]
code = "write-only-property"
start_line = 7
end_line = 7

[[entries."source.php".issues]]
code = "write-only-property"
start_line = 8
end_line = 8

[[entries."source.php".issues]]
code = "write-only-property"
start_line = 9
end_line = 9
