variant = "strict"

[[entries."source.php".issues]]
code = "single-class-per-file"
start_line = 14
end_line = 14

[[entries."source.php".issues]]
code = "single-class-per-file"
start_line = 22
end_line = 22

[[entries."source.php".issues]]
code = "single-class-per-file"
start_line = 24
end_line = 24

[[entries."source.php".issues]]
code = "single-class-per-file"
start_line = 29
end_line = 29

[[entries."source.php".issues]]
code = "single-class-per-file"
start_line = 35
end_line = 35

[[entries."source.php".issues]]
code = "single-class-per-file"
start_line = 41
end_line = 41

[[entries."source.php".issues]]
code = "single-class-per-file"
start_line = 47
end_line = 47

[[entries."source.php".issues]]
code = "single-class-per-file"
start_line = 52
end_line = 52

[[entries."source.php".issues]]
code = "single-class-per-file"
start_line = 57
end_line = 57
