variant = "strict"

[[entries."source.php".issues]]
code = "literal-named-argument"
start_line = 28
end_line = 28

[[entries."source.php".issues]]
code = "literal-named-argument"
start_line = 29
end_line = 29

[[entries."source.php".issues]]
code = "strict-types"
start_line = 0
end_line = 0
