variant = "strict"

[[entries."source.php".issues]]
code = "uninitialized-property"
start_line = 146
end_line = 146

[[entries."source.php".issues]]
code = "uninitialized-property"
start_line = 168
end_line = 168
