variant = "strict"

[[entries."source.php".issues]]
code = "invalid-constant-value"
start_line = 17
end_line = 23

[[entries."source.php".issues]]
code = "invalid-constant-value"
start_line = 28
end_line = 35
