variant = "strict"

[[entries."source.php".issues]]
code = "literal-named-argument"
start_line = 16
end_line = 16

[[entries."source.php".issues]]
code = "literal-named-argument"
start_line = 26
end_line = 26

[[entries."source.php".issues]]
code = "single-class-per-file"
start_line = 20
end_line = 20
