variant = "strict"

[[entries."source.php".issues]]
code = "impossible-condition"
start_line = 15
end_line = 15

[[entries."source.php".issues]]
code = "redundant-comparison"
start_line = 15
end_line = 15
