variant = "strict"

[[entries."source.php".issues]]
code = "file-name"
start_line = 8
end_line = 8

[[entries."source.php".issues]]
code = "no-else-clause"
start_line = 23
end_line = 25

[[entries."source.php".issues]]
code = "no-else-clause"
start_line = 35
end_line = 37
