variant = "strict"

[[entries."source.php".issues]]
code = "literal-named-argument"
start_line = 3
end_line = 3

[[entries."source.php".issues]]
code = "literal-named-argument"
start_line = 6
end_line = 6

[[entries."source.php".issues]]
code = "literal-named-argument"
start_line = 8
end_line = 8

[[entries."source.php".issues]]
code = "strict-types"
start_line = 0
end_line = 0
