variant = "strict"

[[entries."source.php".issues]]
code = "incompatible-constant-visibility"
start_line = 22
end_line = 22

[[entries."source.php".issues]]
code = "incompatible-constant-visibility"
start_line = 33
end_line = 33
