variant = "strict"

[[entries."source.php".issues]]
code = "inline-variable-return"
start_line = 36
end_line = 36

[[entries."source.php".issues]]
code = "literal-named-argument"
start_line = 13
end_line = 13

[[entries."source.php".issues]]
code = "literal-named-argument"
start_line = 26
end_line = 26

[[entries."source.php".issues]]
code = "literal-named-argument"
start_line = 36
end_line = 36

[[entries."source.php".issues]]
code = "literal-named-argument"
start_line = 44
end_line = 44

[[entries."source.php".issues]]
code = "no-else-clause"
start_line = 16
end_line = 18
