variant = "strict"

[[entries."source.php".issues]]
code = "single-class-per-file"
start_line = 6
end_line = 6

[[entries."source.php".issues]]
code = "single-class-per-file"
start_line = 8
end_line = 8

[[entries."source.php".issues]]
code = "single-class-per-file"
start_line = 13
end_line = 13

[[entries."source.php".issues]]
code = "single-class-per-file"
start_line = 20
end_line = 20

[[entries."source.php".issues]]
code = "single-class-per-file"
start_line = 25
end_line = 25

[[entries."source.php".issues]]
code = "single-class-per-file"
start_line = 32
end_line = 32

[[entries."source.php".issues]]
code = "single-class-per-file"
start_line = 41
end_line = 41

[[entries."source.php".issues]]
code = "single-class-per-file"
start_line = 50
end_line = 50

[[entries."source.php".issues]]
code = "single-class-per-file"
start_line = 55
end_line = 55

[[entries."source.php".issues]]
code = "single-class-per-file"
start_line = 62
end_line = 62

[[entries."source.php".issues]]
code = "single-class-per-file"
start_line = 72
end_line = 72

[[entries."source.php".issues]]
code = "single-class-per-file"
start_line = 82
end_line = 82

[[entries."source.php".issues]]
code = "single-class-per-file"
start_line = 92
end_line = 92
