variant = "strict"

[[entries."source.php".issues]]
code = "braced-string-interpolation"
start_line = 10
end_line = 10

[[entries."source.php".issues]]
code = "file-name"
start_line = 2
end_line = 2

[[entries."source.php".issues]]
code = "no-isset"
start_line = 15
end_line = 15

[[entries."source.php".issues]]
code = "no-isset"
start_line = 19
end_line = 19

[[entries."source.php".issues]]
code = "no-isset"
start_line = 23
end_line = 23

[[entries."source.php".issues]]
code = "no-isset"
start_line = 33
end_line = 33

[[entries."source.php".issues]]
code = "no-isset"
start_line = 37
end_line = 37

[[entries."source.php".issues]]
code = "no-isset"
start_line = 47
end_line = 47

[[entries."source.php".issues]]
code = "no-isset"
start_line = 57
end_line = 57

[[entries."source.php".issues]]
code = "no-isset"
start_line = 65
end_line = 65

[[entries."source.php".issues]]
code = "no-isset"
start_line = 82
end_line = 82

[[entries."source.php".issues]]
code = "no-redundant-isset"
start_line = 57
end_line = 57

[[entries."source.php".issues]]
code = "no-redundant-isset"
start_line = 82
end_line = 82

[[entries."source.php".issues]]
code = "strict-types"
start_line = 0
end_line = 0
