variant = "strict"

[[entries."source.php".issues]]
code = "never-return"
start_line = 13
end_line = 13

[[entries."source.php".issues]]
code = "non-existent-class-constant"
start_line = 13
end_line = 13
