variant = "strict"

[[entries."source.php".issues]]
code = "single-class-per-file"
start_line = 12
end_line = 12

[[entries."source.php".issues]]
code = "single-class-per-file"
start_line = 22
end_line = 22

[[entries."source.php".issues]]
code = "single-class-per-file"
start_line = 27
end_line = 27

[[entries."source.php".issues]]
code = "single-class-per-file"
start_line = 34
end_line = 34

[[entries."source.php".issues]]
code = "single-class-per-file"
start_line = 39
end_line = 39

[[entries."source.php".issues]]
code = "single-class-per-file"
start_line = 50
end_line = 50

[[entries."source.php".issues]]
code = "single-class-per-file"
start_line = 55
end_line = 55

[[entries."source.php".issues]]
code = "single-class-per-file"
start_line = 63
end_line = 63

[[entries."source.php".issues]]
code = "single-class-per-file"
start_line = 68
end_line = 68

[[entries."source.php".issues]]
code = "single-class-per-file"
start_line = 80
end_line = 80

[[entries."source.php".issues]]
code = "single-class-per-file"
start_line = 85
end_line = 85

[[entries."source.php".issues]]
code = "single-class-per-file"
start_line = 94
end_line = 94

[[entries."source.php".issues]]
code = "single-class-per-file"
start_line = 99
end_line = 99

[[entries."source.php".issues]]
code = "strict-types"
start_line = 0
end_line = 0
