variant = "strict"

[[entries."source.php".issues]]
code = "function-name"
start_line = 4
end_line = 4

[[entries."source.php".issues]]
code = "function-name"
start_line = 14
end_line = 14

[[entries."source.php".issues]]
code = "function-name"
start_line = 24
end_line = 24
