variant = "strict"

[[entries."source.php".issues]]
code = "less-specific-argument"
start_line = 37
end_line = 37

[[entries."source.php".issues]]
code = "unsafe-instantiation"
start_line = 23
end_line = 23
