variant = "strict"

[[entries."source.php".issues]]
code = "single-class-per-file"
start_line = 8
end_line = 8

[[entries."source.php".issues]]
code = "single-class-per-file"
start_line = 14
end_line = 14

[[entries."source.php".issues]]
code = "single-class-per-file"
start_line = 19
end_line = 19

[[entries."source.php".issues]]
code = "single-class-per-file"
start_line = 25
end_line = 25

[[entries."source.php".issues]]
code = "single-class-per-file"
start_line = 30
end_line = 30

[[entries."source.php".issues]]
code = "single-class-per-file"
start_line = 36
end_line = 36

[[entries."source.php".issues]]
code = "single-class-per-file"
start_line = 41
end_line = 41

[[entries."source.php".issues]]
code = "strict-types"
start_line = 0
end_line = 0
