variant = "strict"

[[entries."source.php".issues]]
code = "duplicate-definition"
start_line = 10
end_line = 13

[[entries."source.php".issues]]
code = "duplicate-definition"
start_line = 19
end_line = 19
