variant = "strict"

[[entries."source.php".issues]]
code = "no-redundant-method-override"
start_line = 28
end_line = 31

[[entries."source.php".issues]]
code = "single-class-per-file"
start_line = 14
end_line = 14

[[entries."source.php".issues]]
code = "single-class-per-file"
start_line = 26
end_line = 26
