variant = "strict"

[[entries."source.php".issues]]
code = "missing-template-parameter"
start_line = 15
end_line = 15

[[entries."source.php".issues]]
code = "unused-template-parameter"
start_line = 9
end_line = 9
