variant = "strict"

[[entries."source.php".issues]]
code = "possibly-undefined-string-array-index"
start_line = 18
end_line = 18

[[entries."source.php".issues]]
code = "possibly-undefined-string-array-index"
start_line = 19
end_line = 19

[[entries."source.php".issues]]
code = "possibly-undefined-string-array-index"
start_line = 20
end_line = 20

[[entries."source.php".issues]]
code = "possibly-undefined-string-array-index"
start_line = 21
end_line = 21

[[entries."source.php".issues]]
code = "redundant-comparison"
start_line = 23
end_line = 23

[[entries."source.php".issues]]
code = "redundant-comparison"
start_line = 26
end_line = 26

[[entries."source.php".issues]]
code = "redundant-condition"
start_line = 23
end_line = 23

[[entries."source.php".issues]]
code = "redundant-condition"
start_line = 26
end_line = 26
