variant = "strict"

[[entries."source.php".issues]]
code = "enum-instantiation"
start_line = 12
end_line = 12

[[entries."source.php".issues]]
code = "impossible-assignment"
start_line = 12
end_line = 12
