variant = "strict"

[[entries."source.php".issues]]
code = "incompatible-property-hook-parameter-type"
start_line = 9
end_line = 9

[[entries."source.php".issues]]
code = "missing-constructor"
start_line = 4
end_line = 4
