variant = "strict"

[[entries."source.php".issues]]
code = "impossible-assignment"
start_line = 8
end_line = 8

[[entries."source.php".issues]]
code = "non-existent-class-constant"
start_line = 8
end_line = 8
