variant = "strict"

[[entries."source.php".issues]]
code = "file-name"
start_line = 2
end_line = 2

[[entries."source.php".issues]]
code = "no-empty-comment"
start_line = 4
end_line = 5

[[entries."source.php".issues]]
code = "strict-types"
start_line = 0
end_line = 0
