variant = "strict"

[[entries."source.php".issues]]
code = "inline-variable-return"
start_line = 77
end_line = 77

[[entries."source.php".issues]]
code = "no-else-clause"
start_line = 55
end_line = 57

[[entries."source.php".issues]]
code = "single-class-per-file"
start_line = 28
end_line = 28

[[entries."source.php".issues]]
code = "single-class-per-file"
start_line = 30
end_line = 30
