variant = "strict"

[[entries."source.php".issues]]
code = "function-name"
start_line = 25
end_line = 25

[[entries."source.php".issues]]
code = "function-name"
start_line = 44
end_line = 44

[[entries."source.php".issues]]
code = "function-name"
start_line = 68
end_line = 68

[[entries."source.php".issues]]
code = "single-class-per-file"
start_line = 56
end_line = 56
