variant = "strict"

[[entries."source.php".issues]]
code = "invalid-argument"
start_line = 33
end_line = 33

[[entries."source.php".issues]]
code = "invalid-argument"
start_line = 93
end_line = 93

[[entries."source.php".issues]]
code = "invalid-argument"
start_line = 103
end_line = 103

[[entries."source.php".issues]]
code = "invalid-return-statement"
start_line = 67
end_line = 67

[[entries."source.php".issues]]
code = "possibly-invalid-argument"
start_line = 24
end_line = 24

[[entries."source.php".issues]]
code = "possibly-invalid-argument"
start_line = 46
end_line = 46
