variant = "strict"

[[entries."source.php".issues]]
code = "invalid-pass-by-reference"
start_line = 15
end_line = 15

[[entries."source.php".issues]]
code = "invalid-return-statement"
start_line = 6
end_line = 6
