variant = "strict"

[[entries."source.php".issues]]
code = "no-empty-comment"
start_line = 2
end_line = 3

[[entries."source.php".issues]]
code = "no-empty-comment"
start_line = 11
end_line = 12

[[entries."source.php".issues]]
code = "strict-types"
start_line = 0
end_line = 0
