variant = "strict"

[[entries."source.php".issues]]
code = "invalid-argument"
start_line = 42
end_line = 42

[[entries."source.php".issues]]
code = "invalid-argument"
start_line = 47
end_line = 47

[[entries."source.php".issues]]
code = "invalid-argument"
start_line = 51
end_line = 51

[[entries."source.php".issues]]
code = "invalid-argument"
start_line = 55
end_line = 55

[[entries."source.php".issues]]
code = "invalid-argument"
start_line = 59
end_line = 59

[[entries."source.php".issues]]
code = "semantics"
start_line = 41
end_line = 41

[[entries."source.php".issues]]
code = "semantics"
start_line = 45
end_line = 45

[[entries."source.php".issues]]
code = "semantics"
start_line = 49
end_line = 49

[[entries."source.php".issues]]
code = "semantics"
start_line = 53
end_line = 53

[[entries."source.php".issues]]
code = "semantics"
start_line = 57
end_line = 57
