variant = "strict"

[[entries."source.php".issues]]
code = "braced-string-interpolation"
start_line = 6
end_line = 6

[[entries."source.php".issues]]
code = "braced-string-interpolation"
start_line = 11
end_line = 11

[[entries."source.php".issues]]
code = "braced-string-interpolation"
start_line = 17
end_line = 17

[[entries."source.php".issues]]
code = "braced-string-interpolation"
start_line = 19
end_line = 19

[[entries."source.php".issues]]
code = "braced-string-interpolation"
start_line = 26
end_line = 26

[[entries."source.php".issues]]
code = "braced-string-interpolation"
start_line = 28
end_line = 28

[[entries."source.php".issues]]
code = "braced-string-interpolation"
start_line = 35
end_line = 35

[[entries."source.php".issues]]
code = "braced-string-interpolation"
start_line = 37
end_line = 37

[[entries."source.php".issues]]
code = "literal-named-argument"
start_line = 42
end_line = 42

[[entries."source.php".issues]]
code = "literal-named-argument"
start_line = 43
end_line = 43

[[entries."source.php".issues]]
code = "literal-named-argument"
start_line = 46
end_line = 46

[[entries."source.php".issues]]
code = "literal-named-argument"
start_line = 47
end_line = 47

[[entries."source.php".issues]]
code = "literal-named-argument"
start_line = 50
end_line = 50

[[entries."source.php".issues]]
code = "literal-named-argument"
start_line = 51
end_line = 51

[[entries."source.php".issues]]
code = "literal-named-argument"
start_line = 54
end_line = 54

[[entries."source.php".issues]]
code = "literal-named-argument"
start_line = 55
end_line = 55

[[entries."source.php".issues]]
code = "literal-named-argument"
start_line = 58
end_line = 58

[[entries."source.php".issues]]
code = "literal-named-argument"
start_line = 59
end_line = 59

[[entries."source.php".issues]]
code = "no-boolean-flag-parameter"
start_line = 14
end_line = 14

[[entries."source.php".issues]]
code = "no-boolean-flag-parameter"
start_line = 23
end_line = 23

[[entries."source.php".issues]]
code = "no-boolean-flag-parameter"
start_line = 32
end_line = 32

[[entries."source.php".issues]]
code = "no-else-clause"
start_line = 18
end_line = 20

[[entries."source.php".issues]]
code = "no-else-clause"
start_line = 27
end_line = 29

[[entries."source.php".issues]]
code = "no-else-clause"
start_line = 36
end_line = 38

[[entries."source.php".issues]]
code = "semantics"
start_line = 41
end_line = 41

[[entries."source.php".issues]]
code = "semantics"
start_line = 45
end_line = 45

[[entries."source.php".issues]]
code = "semantics"
start_line = 49
end_line = 49

[[entries."source.php".issues]]
code = "semantics"
start_line = 53
end_line = 53

[[entries."source.php".issues]]
code = "semantics"
start_line = 57
end_line = 57
