variant = "strict"

[[entries."source.php".issues]]
code = "literal-named-argument"
start_line = 5
end_line = 5

[[entries."source.php".issues]]
code = "no-assign-in-condition"
start_line = 5
end_line = 5
