[package]
name = "mago-wasm"
description = "Exposes PHP code analysis and tooling functionalities as WebAssembly modules, enabling browser-based tools and editor integrations."
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
mago-syntax = { workspace = true }
mago-interner = { workspace = true }
mago-reporting = { workspace = true }
mago-project = { workspace = true }
mago-source = { workspace = true }
mago-php-version = { workspace = true }
mago-linter = { workspace = true }
mago-formatter = { workspace = true }
wasm-bindgen = { workspace = true }
serde-wasm-bindgen = { workspace = true }
serde = { workspace = true }
