variant = "strict"

[[entries."source.php".issues]]
code = "literal-named-argument"
start_line = 21
end_line = 21

[[entries."source.php".issues]]
code = "no-else-clause"
start_line = 24
end_line = 26

[[entries."source.php".issues]]
code = "strict-types"
start_line = 0
end_line = 0
