variant = "strict"

[[entries."source.php".issues]]
code = "possibly-undefined-string-array-index"
start_line = 8
end_line = 8

[[entries."source.php".issues]]
code = "reference-to-undefined-variable"
start_line = 6
end_line = 6
