variant = "strict"

[[entries."source.php".issues]]
code = "single-class-per-file"
start_line = 9
end_line = 9

[[entries."source.php".issues]]
code = "single-class-per-file"
start_line = 16
end_line = 16

[[entries."source.php".issues]]
code = "single-class-per-file"
start_line = 21
end_line = 21

[[entries."source.php".issues]]
code = "single-class-per-file"
start_line = 29
end_line = 29

[[entries."source.php".issues]]
code = "single-class-per-file"
start_line = 34
end_line = 34

[[entries."source.php".issues]]
code = "single-class-per-file"
start_line = 41
end_line = 41

[[entries."source.php".issues]]
code = "single-class-per-file"
start_line = 46
end_line = 46

[[entries."source.php".issues]]
code = "single-class-per-file"
start_line = 56
end_line = 56

[[entries."source.php".issues]]
code = "single-class-per-file"
start_line = 61
end_line = 61

[[entries."source.php".issues]]
code = "single-class-per-file"
start_line = 70
end_line = 70

[[entries."source.php".issues]]
code = "single-class-per-file"
start_line = 75
end_line = 75

[[entries."source.php".issues]]
code = "single-class-per-file"
start_line = 83
end_line = 83

[[entries."source.php".issues]]
code = "single-class-per-file"
start_line = 88
end_line = 88

[[entries."source.php".issues]]
code = "single-class-per-file"
start_line = 95
end_line = 95

[[entries."source.php".issues]]
code = "single-class-per-file"
start_line = 100
end_line = 100

[[entries."source.php".issues]]
code = "single-class-per-file"
start_line = 107
end_line = 107

[[entries."source.php".issues]]
code = "single-class-per-file"
start_line = 112
end_line = 112

[[entries."source.php".issues]]
code = "single-class-per-file"
start_line = 121
end_line = 121

[[entries."source.php".issues]]
code = "single-class-per-file"
start_line = 129
end_line = 129

[[entries."source.php".issues]]
code = "single-class-per-file"
start_line = 138
end_line = 138

[[entries."source.php".issues]]
code = "strict-types"
start_line = 0
end_line = 0
