use indoc::indoc;
use schemars::JsonSchema;
use serde::Deserialize;
use serde::Serialize;

use mago_reporting::Annotation;
use mago_reporting::Issue;
use mago_reporting::Level;
use mago_span::HasSpan;
use mago_syntax::ast::Hint;
use mago_syntax::ast::Node;
use mago_syntax::ast::NodeKind;

use crate::category::Category;
use crate::context::LintContext;
use crate::integration::Integration;
use crate::requirements::RuleRequirements;
use crate::rule::Config;
use crate::rule::LintRule;
use crate::rule_meta::RuleMeta;
use crate::settings::RuleSettings;

const DISCOURAGED_SUFFIXES: &[&str] = &["Proxy", "Interceptor"];

#[derive(Debug, Clone)]
pub struct NoProxyInterceptorInConstructorRule {
    meta: &'static RuleMeta,
    cfg: NoProxyInterceptorInConstructorConfig,
}

#[derive(Debug, Clone, Copy, Eq, PartialEq, Hash, Serialize, Deserialize, JsonSchema)]
#[serde(default, rename_all = "kebab-case", deny_unknown_fields)]
pub struct NoProxyInterceptorInConstructorConfig {
    pub level: Level,
}

impl Default for NoProxyInterceptorInConstructorConfig {
    fn default() -> Self {
        Self { level: Level::Error }
    }
}

impl Config for NoProxyInterceptorInConstructorConfig {
    fn level(&self) -> Level {
        self.level
    }
}

impl LintRule for NoProxyInterceptorInConstructorRule {
    type Config = NoProxyInterceptorInConstructorConfig;

    fn meta() -> &'static RuleMeta {
        const META: RuleMeta = RuleMeta {
            name: "No Proxy/Interceptor In Constructor",
            code: "no-proxy-interceptor-in-constructor",
            description: indoc! {"
                Flags type hints that reference Proxy or Interceptor classes. In Magento 2,
                Proxy and Interceptor classes are auto-generated by the framework. They should
                be configured in `di.xml`, not referenced directly in PHP code.
            "},
            good_example: indoc! {r"
                <?php

                namespace Vendor\Module\Model;

                use Magento\Catalog\Api\ProductRepositoryInterface;

                class Example
                {
                    public function __construct(
                        private ProductRepositoryInterface $productRepository,
                    ) {}
                }
            "},
            bad_example: indoc! {r"
                <?php

                namespace Vendor\Module\Model;

                use Magento\Catalog\Api\ProductRepositoryInterface\Proxy;

                class Example
                {
                    public function __construct(
                        private Proxy $productRepository,
                    ) {}
                }
            "},
            category: Category::BestPractices,
            requirements: RuleRequirements::Integration(Integration::Magento),
        };

        &META
    }

    fn targets() -> &'static [NodeKind] {
        const TARGETS: &[NodeKind] = &[NodeKind::Hint];

        TARGETS
    }

    fn build(settings: &RuleSettings<Self::Config>) -> Self {
        Self { meta: Self::meta(), cfg: settings.config }
    }

    fn check<'arena>(&self, ctx: &mut LintContext<'_, 'arena>, node: Node<'_, 'arena>) {
        let Node::Hint(Hint::Identifier(identifier)) = node else {
            return;
        };

        let fqcn = ctx.lookup_name(identifier);

        // Check if the last segment of the class name is Proxy or Interceptor
        let short_name = fqcn.rsplit('\\').next().unwrap_or(fqcn);

        let Some(matched) = DISCOURAGED_SUFFIXES
            .iter()
            .find(|&&suffix| short_name.eq_ignore_ascii_case(suffix))
        else {
            return;
        };

        ctx.collector.report(
            Issue::new(
                self.cfg.level(),
                format!("Direct use of `{matched}` classes is discouraged."),
            )
            .with_code(self.meta.code)
            .with_annotation(
                Annotation::primary(identifier.span())
                    .with_message(format!("`{matched}` classes should be configured in `di.xml`")),
            )
            .with_help(
                "Remove the Proxy/Interceptor type hint and configure lazy loading \
                 in `di.xml` instead.",
            ),
        );
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::test_lint_failure;
    use crate::test_lint_success;

    test_lint_success! {
        name = normal_interface_type_hint,
        rule = NoProxyInterceptorInConstructorRule,
        code = r#"
            <?php

            namespace Vendor\Module\Model;

            use Magento\Catalog\Api\ProductRepositoryInterface;

            class Example
            {
                public function __construct(
                    private ProductRepositoryInterface $productRepository,
                ) {}
            }
        "#
    }

    test_lint_failure! {
        name = proxy_class_type_hint,
        rule = NoProxyInterceptorInConstructorRule,
        code = r#"
            <?php

            namespace Vendor\Module\Model;

            use Magento\Catalog\Api\ProductRepositoryInterface\Proxy;

            class Example
            {
                public function __construct(
                    private Proxy $productRepository,
                ) {}
            }
        "#
    }

    test_lint_failure! {
        name = interceptor_class_type_hint,
        rule = NoProxyInterceptorInConstructorRule,
        code = r#"
            <?php

            namespace Vendor\Module\Model;

            use Magento\Catalog\Model\Product\Interceptor;

            class Example
            {
                public function __construct(
                    private Interceptor $product,
                ) {}
            }
        "#
    }
}
