# Default analyzer settings for integration test cases.

[source]
paths = ["source.php"]
includes = ["vendor.php"]

[linter]
baseline = "linter.baseline.toml"
baseline-variant = "strict"

[analyzer]
baseline = "analyzer.baseline.toml"
baseline-variant = "strict"
