variant = "strict"

[[entries."source.php".issues]]
code = "false-operand"
start_line = 17
end_line = 17

[[entries."source.php".issues]]
code = "possibly-null-operand"
start_line = 8
end_line = 8

[[entries."source.php".issues]]
code = "possibly-null-operand"
start_line = 17
end_line = 17

[[entries."source.php".issues]]
code = "possibly-null-operand"
start_line = 26
end_line = 26

[[entries."source.php".issues]]
code = "possibly-null-operand"
start_line = 44
end_line = 44

[[entries."source.php".issues]]
code = "possibly-null-operand"
start_line = 57
end_line = 57

[[entries."source.php".issues]]
code = "redundant-condition"
start_line = 21
end_line = 21
