variant = "strict"

[[entries."source.php".issues]]
code = "null-array-access"
start_line = 12
end_line = 12

[[entries."source.php".issues]]
code = "possibly-null-array-access"
start_line = 8
end_line = 8

[[entries."source.php".issues]]
code = "possibly-undefined-string-array-index"
start_line = 8
end_line = 8
