variant = "strict"

[[entries."source.php".issues]]
code = "single-class-per-file"
start_line = 11
end_line = 11

[[entries."source.php".issues]]
code = "single-class-per-file"
start_line = 13
end_line = 13
