variant = "strict"

[[entries."source.php".issues]]
code = "literal-named-argument"
start_line = 10
end_line = 10

[[entries."source.php".issues]]
code = "literal-named-argument"
start_line = 15
end_line = 15

[[entries."source.php".issues]]
code = "literal-named-argument"
start_line = 22
end_line = 22

[[entries."source.php".issues]]
code = "no-boolean-flag-parameter"
start_line = 7
end_line = 7

[[entries."source.php".issues]]
code = "strict-types"
start_line = 0
end_line = 0
