variant = "strict"

[[entries."source.php".issues]]
code = "no-empty-comment"
start_line = 4
end_line = 5

[[entries."source.php".issues]]
code = "no-empty-comment"
start_line = 12
end_line = 13

[[entries."source.php".issues]]
code = "no-empty-comment"
start_line = 19
end_line = 20
